config/routes.rb
Fluxday::Application.routes.draw do

  resources :oauth_applications

  use_doorkeeper
  resources :okrs

  get "reports/index"
  get "reports/activities"
  get "reports/employees_daily"
  get "reports/employee_day"
  get "reports/employees_time_range"
  get "reports/employee_range"
  get "reports/tasks"
  get "reports/task"
  get "reports/okrs"
  get "reports/get_selection_list"
  get "reports/employee_tasks"
  get "reports/worklogs"
  get "reports/day_log"
  get "reports/assignments"

  resources :work_logs do
    member do
      post 'delete_request'
      post 'ignore_request'
    end
  end

  get "calendar/index"
  get "calendar/monthly"
  get "calendar/day"
  get "calendar/week"
  resources :comments do
    member do
      get 'reply'
      post 'post_reply'
    end
  end

  resources :tasks do
    resources :comments
    member do
      post 'completion'
    end
    collection do
      get 'completed_index'
    end
  end

  resources :teams do
    get 'add_members'
    post 'add_members'
    collection do
      get 'get_member_list'
    end
  end

  get "home/index"
  get "home/dashboard"
  get "home/search"
  post "home/search"
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  resources :projects do
    resources :teams
  end

  resources :users do
    resources :okrs do
      member do
        post 'approve'
      end
    end
    collection do
      get 'change_password'
      post 'change_password'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/me' => "credentials#me"
    end
  end

  root 'home#index'

end

app/models/task.rb
class Task < ActiveRecord::Base

  extend FriendlyId
  friendly_id :tracker_id

  belongs_to :user
  belongs_to :team
  belongs_to :project
  #has_many :task_assignees
  #has_many :users, :through => :task_assignees
  has_many :comments, :as => :source
  has_many :work_logs
  has_many :task_key_results
  has_many :key_results, :through => :task_key_results
  has_many :users, -> { uniq }, :through => :key_results


  default_scope { where.not(is_deleted: true).order('id desc') }

  before_create :add_tracker_id

  after_save :update_team_task_count
  before_update :update_completion

  belongs_to :root_task, :class_name => "Task", :foreign_key => "task_id"
  has_many :sub_tasks, :class_name => "Task", :foreign_key => "task_id"

  scope :active, -> { where(is_deleted: false) }
  scope :root, -> { where(task_id: nil) }
  scope :sub, -> { where("task_id IS NOT NULL") }
  scope :pending, -> { where(status: 'active') }
  scope :completed, -> { where(status: 'completed') }
  scope :searchable_for_user, lambda { |user| where("id in (?) OR id in (?) OR project_id in (?)  OR team_id in (?)", user.task_ids, user.assignment_ids, user.project_ids, user.team_ids) }
  #scope :, lambda { |user| where("id in (?) OR id in (?) OR project_id in (?)  OR team_id in (?)", user.task_ids, user.assignment_ids ,user.project_ids, user.admin_team_ids)}


  def updatable_by_user(user)
    return true if user_ids.include?(user.id)
    return true if user.admin_team_ids.include?(team_id)
    return true if user.project_ids.include?(project_id)
  end

  def time_to_end
    if end_date.to_date == Date.today
      'Due today'
    elsif end_date <= Date.today
      'Ended on '+end_date.strftime('%d %B %Y')
    elsif end_date <= 7.day.from_now
      rem = (end_date.to_date - Date.today.to_date).to_i
      "#{rem} #{'day'.pluralize(rem)} left"
    else
      'Due '+end_date.strftime('%d %B %Y')
    end
  end


  def update_team_task_count
    team.update_attributes(:pending_tasks => team.tasks.active.pending.count)
  end

  def add_tracker_id
    self.tracker_id = Task.unscoped.last.try(:tracker_id).to_i + 1
  end

  def timestamp
    created_at.strftime('%d %B %Y %H:%M:%S')
  end


  def update_completion
    if self.status? && self.status_changed? && self.status_change[1] == 'completed' and self.status_change[0] == 'active'
      self.completed_on = Time.now
    elsif self.status? && self.status_changed? && self.status_change[1] == 'active' and self.status_change[0] == 'completed'
      self.completed_on = nil
    end
  end

end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :project
  has_many :team_members
  has_many :tasks
  has_many :users, :through => :team_members
  has_many :okrs, :through => :users
  has_many :key_results, :through => :okrs
  has_many :leads, -> { where role: 'lead' }, class_name: 'TeamMember'
  has_many :team_leads, :through => :leads, :source => :user #,:foreign_key=>'user_id'
  has_many :members, -> { uniq }, :through => :team_members, :source => :user

  validates_presence_of :name, :code, :project_id

  default_scope { where.not(is_deleted: true).order("teams.name ASC") }

  scope :active, -> { where(status: 'active') }

  after_save :update_project_team_count

  def update_project_team_count
    project.update_attributes(:team_count => project.teams.active.count)
  end

  def self.for_user(user)
    teams = Team.where("project_id IN (?) OR id IN (?)",user.project_ids,(user.admin_team_ids + user.team_ids).uniq)
  end

  def self.admind_by_user(user)
    teams = Team.where("project_id IN (?) OR id IN (?)",user.project_ids,user.admin_team_ids.uniq)
  end

  def self.assignable_by_user(user)
    teams = Team.where(project_id:(user.project_ids+user.admin_teams.collect(&:project_id).uniq))
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource
  #load_and_authorize_resource :task, :through => [:team,:task], :shallow => true

  # GET /tasks
  # GET /tasks.json
  def index
    #@tasks = current_user.assignments
    @tasks = current_user.watching_tasks.pending.paginate(page: params[:page], per_page: 10)
    @fin_tasks = current_user.watching_tasks.completed.paginate(page: params[:page], per_page: 10) unless params[:page]
  end

  def completed_index
    #@tasks = current_user.assignments
    @fin_tasks = current_user.watching_tasks.completed.paginate(page: params[:page], per_page: 10)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @tasks = current_user.assigned_and_written_tasks.pending.paginate(page: params[:page], per_page: 10)
    @fin_tasks = current_user.watching_tasks.completed.paginate(page: params[:page], per_page: 10) unless params[:page]
    @team = @task.team
    @project = @team.project
    @sub_tasks = @task.sub_tasks
    @comment = @task.comments.new
  end

# GET /tasks/new
  def new
    @root_task = Task.find(params[:task_id]) if params[:task_id].present?
    @team = @root_task.team if params[:task_id].present?
    @task = @root_task.present? ? @root_task.sub_tasks.new : Task.new
    @task.start_date = Time.now
    @task.end_date = Time.now
    if params[:team_id].present?
      @team = Team.find(params[:team_id])
      @task.team_id = @team.id if @team.present?
      @task.project_id = @team.project_id if @team.present?
    end
    @teams = Team.assignable_by_user(current_user).includes(:project)
    @grouped_teams = @teams.inject({}) do |options, team|
      (options[team.project.name] ||= []) << [team.name, team.id]
      options
    end
    @team ||= @teams.first
    if @team.present?
    if (current_user.admin_teams.include?(@team) || current_user.project_ids.include?(@team.project_id))
      @users = @team.members
    else
      @users = @team.team_leads
    end
    else
      redirect_to root_path, :alert => 'You have no access to a team inorder to assign a task.'
    end
    @kr_ids = @task.key_result_ids
    @key_results = @team.key_results.where('key_results.start_date <= ? && key_results.end_date >= ?', @task.end_date, @task.start_date).group_by(&:user_id) if @team
  end

  # GET /tasks/1/edit
  def edit
    @projects = Project.active
    @team ||= @task.team
    @teams = Team.assignable_by_user(current_user).includes(:project)
    @grouped_teams = @teams.inject({}) do |options, team|
      (options[team.project.name] ||= []) << [team.name, team.id]
      options
    end

    @users = @team.try(&:members)
    start_date = @task.start_date
    end_date = @task.end_date
    @kr_ids = @task.key_result_ids
    @key_results = @team.key_results.where('key_results.start_date <= ? && key_results.end_date >= ?', end_date, start_date).group_by(&:user_id)
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.project_id = @task.team.project_id if @task.team.present?
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.update_attribute(:is_deleted, true)
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  def completion
    @task = Task.find(params[:id])
    if request.post?
      @task.update_attributes(:completed_on => params[:task][:completed_on].to_time, :status => 'completed') if (params[:task] && params[:task][:completed_on])
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:name, :description, :start_date, :task_id, :end_date, :project_id, :team_id, :user_id, :tracker_id, :priority, :comments_count, :status, :completed_on, :key_result_ids => [], :user_ids => [])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_completed_task_page.erb
<% if @fin_tasks.present? %>
<% @fin_tasks.each do |task| %>
    <%= link_to task_path(task),:remote=>true do %>
        <div class="card transition task-card task task-<%= task.id %>">
          <div class="name">
            <%= task.name %>
          </div>
          <div class="date end-<%= (task.end_date <= 7.day.from_now && task.end_date >= Date.today) ? 'soon' : 'low' %>">
            <%= task.time_to_end %>
            <div class="right">
              <%= raw("<div class='icon icon-author'></div>") if task.user_id == current_user.id %>
              <%= raw("<div class='icon icon-assignee'></div>") if task.user_ids.include?(current_user.id) %>
            </div>
          </div>
          <div class="team">
            <%= task.team.name %>
          </div>
        </div>
    <% end %>
<% end %>
<% end %>

app/views/tasks/_completion.erb
<div  data-dropdown-content="" style="position: static;">
  <% if task.status == 'completed' %>
      <div class="text-right">Completed on <%= task.completed_on.strftime('%d/%m/%Y %H:%M') %></div>
  <% else %>
      <%= form_for :task, :url => completion_task_path(task.id), :remote => true do |f| %>
          <div class="row task-completion">
            <!--<div class="small-4 columns">-->
            <!--</div>-->
            <!--<div class="small-6 columns">-->
            <button class="button alert right">Done</button>
            <%= f.text_field :completed_on, :value => Time.now.strftime('%d/%m/%Y %H:%M'), :class => 'right' %>
            <%= f.label :completed_on, :class => 'right inline' %>

            <!--</div>-->
            <!--<div class="small-2 columns">-->
            <!--</div>-->
          </div>
      <% end %>
  <% end %>
</div>

app/views/tasks/_form.html.erb
<% if @team.present? %>
    <%= form_for @task, :html => {:class => 'form-horizontal task-form', :multipart => true, :data => {:abide => true}} do |f| %>
        <div class="form-content form-below">
          <%= f.hidden_field :task_id, :value => @root_task.id if @root_task.present? %>
          <%= f.hidden_field :team_id, :value => @root_task.team_id if @root_task.present? %>
          <%= f.hidden_field :project_id, :value => @root_task.project_id if @root_task.present? %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= build_validated_field('task', 'name', 'Title', 'Cannot be blank', '', 'text', @task.name) %>
          <%= build_field('task', 'description', 'Description', 'text_area', @task.description) %>
          <%#= build_validated_field('task', 'description', 'Description', 'Cannot be blank', '', 'text_area', @task.description) %>
          <% unless @root_task.present? %>
              <div class='form-row'>
                <div class='small-3 columns'>
                  <%= f.label :team_id, 'Team' %>
                </div>
                <div class='small-9 columns'>
                  <%= select_tag "task[team_id]", grouped_options_for_select(@grouped_teams, @team.id) %>
                  <%#= grouped_collection_select(:task, :team_id, @projects, @teams, :name, :id, :name, {}, {:class => "team-selector"}) %>
                </div>
              </div>
          <% end %>
          <%= build_validated_field('task', 'start_date', 'Start Date', 'Cannot be blank', '', 'date_field', @task.start_date) %>
          <%= build_validated_field('task', 'end_date', 'End Date', 'Cannot be blank', '', 'date_field', @task.end_date) %>
          <% if @task.status == 'completed' %>
              <div class='form-row'>
                <div class='small-3 columns'>
                  <%= f.label :status, 'Status' %>
                </div>
                <div class='small-9 columns'>
                  <%= select_tag('task[status]', options_for_select([['Pending', 'active'], ['Completed', 'completed']], @task.status)) %>
                </div>
              </div>
          <% end %>
          <%#= build_validated_select('task', 'project_id', 'Project','Should select at least one','',false,@task.project_id,Project.active.map{|x| [x.name,x.id]}) %>
          <%#= build_validated_select('task', 'team_id', 'Team','Should select at least one','',false,@task.team_id,Team.active.map{|x| [x.name,x.id]}) %>
          <div class="priority-selector">
            <%= build_validated_select('task', 'priority', 'Priority', 'Should select at least one', '', false, @task.priority, ['Low', 'Medium', 'High', 'Showstopper']) %>
          </div>
          <div class="assignees-select">
            <%= render :partial => 'teams/members' %>

            <%#= build_validated_select('task', 'user_ids', 'Assignees', 'Should select at least one', '', true, @task.user_ids, (@users.nil? ? [] : @users.map { |x| [x.name, x.id] })) %>
          </div>
          <!--<div class="field">-->
          <%#= f.label :tracker_id %>
          <br>
          <!--<%#= f.text_field :tracker_id %>-->
          <!--</div>-->
          <!--<div class="field">-->
          <%#= f.label :comments_count %>
          <br>
          <!--<%#= f.number_field :comments_count %>-->
          <!--</div>-->
        </div>
        <div class="small-12 columns form-action-up">
          <div class="title">Task</div>
          <div class="right">
            <%= f.submit nil, :class => 'button alert right', :disable_with => "Saving" %>
            <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                        tasks_path, :class => 'btn cancel-btn' %>
          </div>
        </div>
    <% end %>
<% else %>
    <div class="message">
      You have no access to a team inorder to assign a task.
    </div>
<% end %>

<script type="text/javascript">
    window.location = '#pane3'
    $('select').not('.select_add').select2({'width': '100%'});
    //    $('.date-input').datetimepicker();
    $('.team-selector').on("change", function () {
        load_assignees()
//        $.get('/teams/get_member_list?team_id=' + $(this).val())
    });

    //    $('.date-input').datetimepicker().on('onChangeDateTime', function () {load_assignees()});

    $('.date-input').datetimepicker({
        onSelectDate: function () {
            load_assignees();
        }
    });

    $('#task_team_id').bind("change", function () {
        load_assignees()
    });
    $('#task_start_date').bind("input", function () {
        load_assignees()
    });
    $('#task_end_date').bind("input", function () {
        load_assignees()
    });
    function load_assignees() {
        if ($('#task_team_id').val() == '' || $('#task_start_date').val() == '' || $('#task_end_date').val() == '') {
            $('.assignees-select').html('Choose end date, start date and team for the task');
        } else {
            $('.assignees-select').html('satisfied');
            $.get('/teams/get_member_list?team_id=' + $('#task_team_id').val() + '&start_date=' + $('#task_start_date').val() + '&end_date=' + $('#task_end_date').val() + "&task_id=<%= @task.try(&:id) %>")
        }
    }
</script>

app/views/tasks/_show.erb
<div class="task-show">
  <div class="task-details">
    <div class="bc-div">
      <ul class="tracker-breadcrumbs">
        <li><%= link_to project.name, project_path(project) %></li>
        <li> ></li>
        <li><%= link_to team.name, project_team_path(project, team) %></li>
        <li> ></li>
        <%= link_to "##{task.tracker_id}", task_path(task) %>
      </ul>
      <div class="right">
        <% unless task.status == 'completed' %>
            <a class="button alert right status" data-options="align:left" data-dropdown="contentDrop-<%= task.id %>">
              <div class="icon completion-link"></div>
            </a>
        <% else %>
            <a class="right" data-options="align:left" data-dropdown="contentDrop-<%= task.id %>">
              <div class="icon completed-link"></div>
            </a>
        <% end %>

        <% if task.updatable_by_user(current_user) %>
            <div id="contentDrop-<%= task.id %>" data-dropdown-content class="f-dropdown content small completion-option completion-area drop-task-<%= task.id %>" style="display: block">
              <%= render :partial => 'tasks/completion', :locals => {:task => task} %>
            </div>
        <% end %>
        <% if can? :edit, task %>
            <a data-options="align:left" data-dropdown="drop-<%= task.id %>" class="dropdown right">
              <div class="icon settings-link"></div>
            </a>
            <ul id="drop-<%= task.id %>" data-dropdown-content class="f-dropdown">
              <li>
                <%= link_to "Edit", edit_task_path(task) %>
              </li>
              <li>
                <%= link_to "Delete", task_path(task), :method => :delete %>
              </li>
            </ul>
        <% end %>

        <div class="date right end-<%= (task.end_date <= 7.day.from_now && task.end_date >= Date.today) ? 'soon' : 'low' %>">
          <%= task.time_to_end %>
        </div>
      </div>
    </div>

    <div class="task-name">
      <%= task.name %>
    </div>

    <div class="info">
      <div class="icon icon-author"></div> Added by
      <em><%= task.user.name %></em>
      on
      <em><%= task.created_at.strftime('%d %B %Y') %></em>
      <span class="task-priority priority-<%= task.priority %>">
        Priority: <%= task.priority %>
      </span>
    </div>

    <div class="descr">
      <%= task.description %>
    </div>

    <div class="info">
      <div class="icon icon-timer"></div> Start date:
      <em><%= task.start_date.strftime('%d %B %Y') %>, </em>
      End date:
      <em><%= task.end_date.strftime('%d %B %Y') %></em>
    </div>


    <div class="info">
      <div class="icon icon-assignee"></div> Assigned to
      <em>
        <% task.users.each_with_index do |u, i| %>
            <%= link_to u.name, user_path(u) %>
            <%= i+1 != task.users.count ? "," : '' %>
        <% end %>
      </em>
    </div>
  </div>

  <div class="comments-link comments-<%= task.id %>">
    <% if @comment.present? %>
        <%= render :partial => 'comments/form' %>
    <% end %>
    <%= link_to "#{task.comments_count.to_i} #{'comment'.pluralize(task.comments_count.to_i)}", task_comments_path(task), :remote => true %>
  </div>

  <% if @sub_tasks.present? %>
      <% @sub_tasks.each_with_index do |task, i| %>
          <%= render :partial => 'tasks/sub_task', :locals => {:task => task, :count => i+1} %>
      <% end %>
  <% end %>
  <% unless task.task_id.present? %>
      <% if can? :manage, task %>
          <%= link_to 'Add subtask', new_task_path(:task_id => task.id), :class => 'dashed_link transition' %>
      <% end %>
  <% end %>

</div>

<script type="text/javascript">
    $('.task.card').removeClass('active')
    $('.task-<%= task.id %>').addClass('active')
    $(window).scrollTop($('#pane3').offset().top)
    $(document).foundation();
</script>

app/views/tasks/_show_detailed.erb
<div class="pane3-meta">
  <div class="title">
    #<%= @task.tracker_id %>
  </div>
</div>
<div class="pane3-content">
  <%= render :partial=>'tasks/show',:locals=>{:task=>task,:project=>project,:team=>team}  %>
</div>

app/views/tasks/_sub_task.erb
<div class="subtask">
  Subtask
  <%= count %>:
  <%= link_to task.name,task_path(task) %>

  <div class="info">
    <div class="icon icon-author"></div> Added by
    <em><%= task.user.name %></em>
    on
    <em><%= task.created_at.strftime('%d %B %Y') %></em>
      <span class="task-priority priority-<%= task.priority %>">
        Priority: <%= task.priority %>
      </span>
  </div>

  <div class="info">
    <div class="icon icon-timer"></div> Start date
    <em><%= task.start_date.strftime('%d %B %Y') %></em>
    End date
    <em><%= task.end_date.strftime('%d %B %Y') %></em>
  </div>

  <div class="info">
    <div class="icon icon-assignee"></div> Assigned to
    <em>
      <% task.users.each_with_index do |u, i| %>
          <%= link_to u.name, user_path(u) %>
          <%= i+1 != task.users.count ? "," : '' %>
      <% end %>
    </em>
  </div>
</div>

app/views/tasks/_task_list.erb
<div class="pane2-meta">
  <div class="title">My tasks</div>
  <dl class="tabs right" data-tab >
    <dd class="active clear-tab"><a href="#pending">
      Pending
    </a></dd>
    <dd class="clear-tab"><a href="#completed">
      Completed
    </a></dd>
  </dl>
</div>

  <div class="data-container">
    <div class="tabs-content">
      <div class="content active" id="pending">
        <div class="task-list" id="my-tasks">
          <div class="pane2-content scroll2watch">
          <div id="paginator" class="paginator task-paginator">
            <%= render :partial => 'tasks/task_page' %>
          </div>
          <div id="infinite-scrolling" class="scroll-loop">
            <%= will_paginate(@tasks, :params => {:controller => "tasks", :action => "index"}) %>
          </div>
          </div>
        </div>
      </div>
      <div class="content" id="completed">
        <div class="task-list" id="my-tasks">
          <div class="pane2-content scroll2watch this">
            <div id="paginator"  class="paginator fin-task-paginator">
              <%= render :partial => 'tasks/completed_task_page' %>
            </div>
            <div id="infinite-scrolling" class="scroll-loop">
              <%= will_paginate(@fin_tasks, :params => {:controller => "tasks", :action => "completed_index"}) %>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
<script type="text/javascript">
    infiniteScroll()
</script>

app/views/tasks/_task_page.erb
<% @tasks.each do |task| %>
    <%= link_to task_path(task),:remote=>true do %>
        <div class="card transition task-card task task-<%= task.id %>">
          <div class="name">
            <%= task.name %>
          </div>
          <div class="date end-<%= (task.end_date <= 7.day.from_now && task.end_date >= Date.today) ? 'soon' : 'low' %>">
            <%= task.time_to_end %>
            <div class="right">
              <%= raw("<div class='icon icon-author'></div>") if task.user_id == current_user.id %>
              <%= raw("<div class='icon icon-assignee'></div>") if task.user_ids.include?(current_user.id) %>
            </div>
          </div>
          <div class="team">
            <%= task.team.name %>
          </div>
        </div>
    <% end %>
<% end %>

app/views/tasks/completed_index.js.erb
$('.fin-task-paginator').append('<%= j render 'tasks/completed_task_page' %>');
<% if @fin_tasks.next_page %>
$('#completed .pagination').replaceWith('<%= j will_paginate @fin_tasks %>');
<% else %>
$(window).off('scroll');
$('#completed .pagination').remove();
<% end %>

app/views/tasks/completion.js.erb
$('.completion-area.drop-task-<%= @task.id %>').html("<%= escape_javascript(render :partial => 'tasks/completion',:locals => {:task => @task}) %>")

app/views/tasks/index.html.erb
<%= content_for :pane2 do %>
<%= render :partial => 'tasks/task_list' %>
<% end %>
<script type="text/javascript">
    window.location = '#pane2'
</script>

app/views/tasks/index.js.erb
$('.task-paginator').append('<%= j render 'tasks/task_page' %>');
<% if @tasks.next_page %>
$('#pending .pagination').replaceWith('<%= j will_paginate @tasks %>');
<% else %>
$(window).off('scroll');
$('#pending .pagination').remove();
<% end %>
window.location = '#pane2'

app/views/tasks/new.js.erb
$('.pane3').html("<%= escape_javascript(render :partial => 'tasks/form') %>")
window.location = '#pane3'

app/views/tasks/show.html.erb
<%= content_for :pane2 do %>
    <%= render :partial => 'tasks/task_list' %>
<% end %>

<div class="pane3-meta">
  <div class="title">
    #<%= @task.tracker_id %>
  </div>
</div>
<div class="pane2-content">

  <%= render :partial => 'show', :locals => {:task => @task, :project => @project, :team => @team} %>
</div>
<script type="text/javascript">
    window.location = '#pane3'
</script>