config/routes.rb
Fluxday::Application.routes.draw do

  resources :oauth_applications

  use_doorkeeper
  resources :okrs

  get "reports/index"
  get "reports/activities"
  get "reports/employees_daily"
  get "reports/employee_day"
  get "reports/employees_time_range"
  get "reports/employee_range"
  get "reports/tasks"
  get "reports/task"
  get "reports/okrs"
  get "reports/get_selection_list"
  get "reports/employee_tasks"
  get "reports/worklogs"
  get "reports/day_log"
  get "reports/assignments"

  resources :work_logs do
    member do
      post 'delete_request'
      post 'ignore_request'
    end
  end

  get "calendar/index"
  get "calendar/monthly"
  get "calendar/day"
  get "calendar/week"
  resources :comments do
    member do
      get 'reply'
      post 'post_reply'
    end
  end

  resources :tasks do
    resources :comments
    member do
      post 'completion'
    end
    collection do
      get 'completed_index'
    end
  end

  resources :teams do
    get 'add_members'
    post 'add_members'
    collection do
      get 'get_member_list'
    end
  end

  get "home/index"
  get "home/dashboard"
  get "home/search"
  post "home/search"
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  resources :projects do
    resources :teams
  end

  resources :users do
    resources :okrs do
      member do
        post 'approve'
      end
    end
    collection do
      get 'change_password'
      post 'change_password'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/me' => "credentials#me"
    end
  end

  root 'home#index'

end

app/models/work_log.rb
class WorkLog < ActiveRecord::Base
  belongs_to :user
  belongs_to :task

  validates_presence_of :task_id
  # validates_inclusion_of :date, :in => 6.day.ago..Date.today,:message=>'Date should be older than 5 days'
  validates_inclusion_of :date, :in => Proc.new{ 6.day.ago..Date.today },:message=>'Date should be older than 5 days'
  #default_scope{ where.not(is_deleted: true) }

  scope :active, -> { where(is_deleted: false) }

  def self.user_logs_dated(user, date)
    user.work_logs.find_by_date(Date.today.to_date)
  end

  def hours
    return "#{self.minutes.to_i/60}:#{ '%02d' % (self.minutes.to_i%60)}"
  end
end

app/controllers/work_logs_controller.rb
class WorkLogsController < ApplicationController
  before_action :set_work_log, only: [:show, :edit, :update, :destroy, :delete_request, :ignore_request]

  # GET /work_logs
  # GET /work_logs.json
  def index
    @work_logs = WorkLog.active
  end

  # GET /work_logs/1
  # GET /work_logs/1.json
  def show
    @tasks = current_user.assigned_and_written_tasks.pending.paginate(page: params[:page], per_page: 10)
    @fin_tasks = current_user.watching_tasks.completed.paginate(page: params[:page], per_page: 10) unless params[:page]
  end

  # GET /work_logs/new
  def new
    unless params[:date].present?
      @date = Date.today
    else
      @date = params[:date].to_date
    end
    @entries = current_user.assignments.where('tasks.start_date <= ? && tasks.end_date >= ?', @date.end_of_day, @date.beginning_of_day)
    @date = params[:date].present? ? params[:date].to_date : Date.today
    @work_log = WorkLog.new(:date => @date)
    @hours = @work_log.minutes.to_i/60
    @mins = @work_log.minutes.to_i%60
  end

  # GET /work_logs/1/edit
  def edit
    @date = @work_log.date
    @entries = Task.where('start_date <= ? && end_date >= ?', @work_log.date.end_of_day, @work_log.date.beginning_of_day)
    @hours = @work_log.minutes.to_i/60
    @mins = @work_log.minutes.to_i%60
  end

  # POST /work_logs
  # POST /work_logs.json
  def create
    @work_log = WorkLog.new(work_log_params)
    @work_log.user_id = current_user.id
    @work_log.minutes = params[:work_log][:hours].to_i*60+params[:work_log][:mins].to_i
    unless params[:date].present?
      @date = Date.today
    else
      @date = params[:date].to_date
    end
    @entries = current_user.assignments.where('tasks.start_date <= ? && tasks.end_date >= ?', @date.end_of_day, @date.beginning_of_day)
    @date = params[:date].present? ? params[:date].to_date : Date.today
    @hours = @work_log.minutes.to_i/60
    @mins = @work_log.minutes.to_i%60
    respond_to do |format|
      if @work_log.save
        format.html { redirect_to @work_log, notice: 'Work log was successfully created.' }
        format.json { render action: 'show', status: :created, location: @work_log }
        format.js { render :layout => false }
      else
        format.js { render :layout => false }
        format.html { render action: 'new' }
        format.json { render json: @work_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_logs/1
  # PATCH/PUT /work_logs/1.json
  def update
    @work_log.minutes = params[:work_log][:hours].to_i*60+params[:work_log][:mins].to_i
    respond_to do |format|
      if @work_log.update(work_log_params)
        format.html { redirect_to @work_log, notice: 'Work log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @work_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_logs/1
  # DELETE /work_logs/1.json
  def destroy
    if @work_log.user == current_user && @work_log.date >= 4.days.ago
      @work_log.destroy
    elsif @work_log.user == current_user
      flash[:notice] = "Log is older than 5 days"
    elsif current_user.manager?
      flash[:notice] = "Worklog deleted"
      @work_log.destroy
    else
      flash[:notice] = "Permission denied"
    end
    respond_to do |format|
      unless current_user.manager?
        format.html { redirect_to root_url }
      else
        format.html { redirect_to reports_worklogs_path }
      end
      format.json { head :no_content }
    end
  end

  def delete_request
    if @work_log.user_id == current_user.id and @work_log.update_attribute(:delete_request,true)
      flash[:notice] = "Delete Request has been made."
    else
      flash[:notice] = "Delete Request could not be made."
    end
    respond_to do |format|
      format.html { redirect_to reports_worklogs_path }
      format.json { head :no_content }
    end
  end

  def ignore_request
    if current_user.manager? and @work_log.update_attribute(:delete_request,false)
      flash[:notice] = "Delete Request has been ignored."
    else
      flash[:notice] = "Delete Request could not be ignored."
    end
    respond_to do |format|
      format.html { redirect_to reports_worklogs_path }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_work_log
    @work_log = WorkLog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def work_log_params
    params.require(:work_log).permit(:user_id, :name, :description, :start_time, :date, :end_time, :is_deleted, :task_id, :delete_request)
  end
end

app/helpers/work_logs_helper.rb
module WorkLogsHelper
end

app/views/work_logs/_form.html.erb
<% unless @entries.empty? %>
    <%= form_for @work_log, :html => {:class => 'form-horizontal', :multipart => true, :data => {:abide => true}, :remote => true} do |f| %>

        <div class="form-content form-below">
          <% if @work_log.errors.any? %>
              <div id="error_explanation">
                <% @work_log.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
                <!--</ul>-->
              </div>
          <% end %>
          <%= f.hidden_field :date, :value => @date %>
          <%#= build_validated_field('work_log', 'name', 'Name', 'Cannot be blank', '[a-zA-Z]+', 'text',@work_log.name) %>
          <%= build_validated_select('work_log', 'task_id', 'Task', 'Should select at least one', '', false, @work_log.task_id, @entries.map { |x| [x.name, x.id] }) %>
          <div class='form-row time-taken'>
            <div class='small-3 columns'>
              <%= f.label :minutes, 'Time taken' %>
            </div>
            <div class="small-9 columns">
              <%= label_tag('work_log[hours]', 'Hours :', :class => 'left') %>
              <div class='small-2 columns left'>
                <%= select_tag 'work_log[hours]', options_for_select((0..23).to_a, @hours) %>
              </div>
              <%= label_tag('work_log[mins]', 'Minutes :', :class => 'left') %>
              <div class='small-2 columns left'>
                <%= select_tag 'work_log[mins]', options_for_select((0..59).to_a, @mins) %>
              </div>
            </div>
          </div>
          <%= build_field('work_log', 'description', 'Description', 'text_area', @work_log.description) %>
          <%#= build_validated_field('work_log', 'start_time', 'Start Time', 'Cannot be blank', '', 'date_field',@work_log.start_time) %>
          <%#= build_validated_field('work_log', 'end_time', 'End Time', 'Cannot be blank', '', 'date_field',@work_log.end_time) %>
          <%#= build_validated_field('work_log', 'is_deleted', 'Deleted', 'Cannot be blank', '', 'checkbox',@work_log.is_deleted) %>
        </div>


        <div class="small-12 columns form-action-up">
          <div class="title">log for <%= @work_log.date.strftime('%d %B %Y') %></div>
          <div class="right">
            <%= f.submit 'Save', :class => 'button alert right',:disable_with=>"Saving" %>
            <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                        root_path, :class => 'btn cancel-btn' %>
          </div>
        </div>
    <% end %>
<% else %>
    <script type="text/javascript">
        $('.alert-area').notify({message: { text: '<%= "You have no task assigned for #{@date.strftime('%d %B %Y')}" %>' }, type: 'tracker-alert', fadeOut: { enabled: true, delay: 10000 }}).show();
    </script>
<% end %>

<script type="text/javascript">
    window.location = '#pane3'
    $('select').select2({'width': '100%'});
    $('.date-input').datetimepicker();
    $('.time-field').timepicker({ 'step': 15 });
    $('textarea').autosize();
</script>

app/views/work_logs/_logs.erb
<div class="logs">
  <div class="title">
    <% unless @work_logs.empty? %>
        Log
    <% end %>
  </div>
  <% @work_logs.each do |log| %>
      <%= link_to work_log_path(log), :remote => true do %>
          <div class="card-transparent transition log-<%= log.id %>">
            <div class="left">
              <%= log.task.try(&:name) %>
            </div>
            <div class="right">
              <%= log.hours %>
            </div>
          </div>
      <% end %>
  <% end %>
</div>

app/views/work_logs/_show.erb
<div class="pane3-meta">
  <div class="title">
    Log
  </div>

  <div class="right options">
    <% if @work_log.user == current_user %>
        <%= link_to raw("<div class='icon remove-link'></div>"), work_log_path(@work_log), :method => :delete, :confirm => 'Are you sure you want to remove this log?' %>
    <% end %>
  </div>
</div>

<div class="pane3-content work-log-show">
  <div class="row">
    <div class="one-row">
      <div class="small-3 columns">Date</div>
      <div class="small-9 columns"><%= @work_log.date.strftime('%d %B %Y') %></div>
    </div>
    <div class="one-row">
      <div class="small-3 columns">User</div>
      <div class="small-9 columns"><%= link_to @work_log.user.name, user_path(@work_log.user_id) %></div>
    </div>
    <div class="one-row">
      <div class="small-3 columns">Time taken</div>
      <div class="small-9 columns"><%= @work_log.hours %></div>
    </div>
    <div class="one-row">
      <div class="small-3 columns">Task</div>
      <div class="small-9 columns"><%= link_to @work_log.task.name, task_path(@work_log.task) %></div>
    </div>
    <div class="one-row">
      <div class="small-3 columns">Description</div>
      <div class="small-9 columns"><%= @work_log.description %></div>
    </div>
  </div>
</div>


<script type="text/javascript">
    $('.logs .card-transparent').removeClass('active')
    $('.log-<%= @work_log.id %>').addClass('active')
    window.location = '#pane3'
</script>

app/views/work_logs/create.js.erb
<% if @work_log.present? && @work_log.id.present? %>
$('.pane3').html("<%= escape_javascript(render :partial => 'work_logs/show') %>")
$('.date-card.date-<%= @work_log.date.to_s %> .entries ul').append('<li><%= link_to "#{@work_log.task.try(&:name)}(#{@work_log.hours})", work_log_path(@work_log), :remote => true %></li>')
$('.alert-area').notify({message: { text: "Log added successfully" }, type: 'tracker-alert', fadeOut: { enabled: true, delay: 30000 }}).show();
<% else %>
<% unless @entries.empty? %>
$('.pane3').html("<%= escape_javascript(render :partial => 'work_logs/form') %>")
<% else %>
$('.alert-area').notify({message: { text: '<%= "You have no task assigned for #{@date.strftime('%d %B %Y')}" %>' }, type: 'tracker-alert', fadeOut: { enabled: true, delay: 10000 }}).show();
<% end %>
<% end %>
$(document).foundation({
    tab: {
        callback: function (tab) {
        }
    }
});
window.location = '#pane3'

app/views/work_logs/edit.html.erb
<%#= render 'form' %>
<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/work_logs/index.html.erb
<h1>Listing work_logs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Task</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Is deleted</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @work_logs.each do |work_log| %>
      <tr>
        <td><%= work_log.user_id %></td>
        <td><%= work_log.name %></td>
        <td><%= work_log.task %></td>
        <td><%= work_log.start_time %></td>
        <td><%= work_log.end_time %></td>
        <td><%= work_log.is_deleted %></td>
        <td><%= link_to 'Show', work_log %></td>
        <td><%= link_to 'Edit', edit_work_log_path(work_log) %></td>
        <td><%= link_to 'Destroy', work_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work log', new_work_log_path %>
<script type="text/javascript">
    window.location = '#pane2'
</script>

app/views/work_logs/new.html.erb
<%= render 'form' %>
<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/work_logs/new.js.erb
<% unless @entries.empty? %>
$('.pane3').html("<%= escape_javascript(render :partial => 'work_logs/form') %>")
<% else %>
$('.alert-area').notify({message: { text: '<%= "You have no task assigned for #{@date.strftime('%d %B %Y')}" %>' }, type: 'tracker-alert', fadeOut: { enabled: true, delay: 10000 }}).show();
<% end %>
$(document).foundation({
    tab: {
        callback: function (tab) {
        }
    }
});
window.location = '#pane3'

app/views/work_logs/show.html.erb
<%= content_for :pane2 do %>
    <%= render :partial => 'tasks/task_list' %>
<% end %>

<%= render :partial => 'show' %>
<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/work_logs/show.js.erb
$('.pane3').html("<%= escape_javascript(render :partial => 'work_logs/show',:locals => {:task => @task, :project => @project, :team => @team}) %>")
window.location = '#pane3'