config/routes.rb
Fluxday::Application.routes.draw do

  resources :oauth_applications

  use_doorkeeper
  resources :okrs

  get "reports/index"
  get "reports/activities"
  get "reports/employees_daily"
  get "reports/employee_day"
  get "reports/employees_time_range"
  get "reports/employee_range"
  get "reports/tasks"
  get "reports/task"
  get "reports/okrs"
  get "reports/get_selection_list"
  get "reports/employee_tasks"
  get "reports/worklogs"
  get "reports/day_log"
  get "reports/assignments"

  resources :work_logs do
    member do
      post 'delete_request'
      post 'ignore_request'
    end
  end

  get "calendar/index"
  get "calendar/monthly"
  get "calendar/day"
  get "calendar/week"
  resources :comments do
    member do
      get 'reply'
      post 'post_reply'
    end
  end

  resources :tasks do
    resources :comments
    member do
      post 'completion'
    end
    collection do
      get 'completed_index'
    end
  end

  resources :teams do
    get 'add_members'
    post 'add_members'
    collection do
      get 'get_member_list'
    end
  end

  get "home/index"
  get "home/dashboard"
  get "home/search"
  post "home/search"
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  resources :projects do
    resources :teams
  end

  resources :users do
    resources :okrs do
      member do
        post 'approve'
      end
    end
    collection do
      get 'change_password'
      post 'change_password'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/me' => "credentials#me"
    end
  end

  root 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :teams
  has_many :tasks
  has_many :project_managers
  has_many :users,:through=>:project_managers,:after_remove => :update_user_project_count
  has_many :team_members, :through => :teams
  has_many :project_members, :through=>:team_members, :source=>:user
  scope :active, -> {where(is_deleted: false)}

  validates_presence_of :name, :code
  validates_uniqueness_of :code

  #default_scope where(is_deleted: false)
  default_scope{ order("projects.name ASC")}

  #after_save  :update_numbers

  def members
    return project_members.active.uniq
  end

  def update_user_project_count(pm)
    pm.update_attributes(:admin_projects_count=>pm.projects.count)
  end

  def update_numbers
    update_attributes(:team_count=>self.teams.count)
  end

  def destroy
    if self.update_attribute(:is_deleted, true)
      self.teams.update_all(:is_deleted => true)
      self.teams.update_all(:is_deleted => true)
      self.tasks.update_all(:is_deleted => true)
      self.team_members.update_all(:status => 'archived')
      self.project_managers.update_all(:status => 'archived')
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.active
    @project = @projects.first unless @projects.empty?
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @projects = Project.active
    @teams = @project.teams
    @managers = @project.users.by_name
    @members = @project.members.where('').map{|x| x}.sort{|a,b| a.name<=>b.name}
  end

  # GET /projects/new
  def new
    @projects = Project.active
    @project = Project.new
    @users= User.active
  end

  # GET /projects/1/edit
  def edit
    @projects = Project.active

    @users= User.active
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @users= User.active

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @users= User.active
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit! #(:name, :code, :description, :is_deleted, :team_count, :member_count, :website, :image)
    #params.require(:project).permit(:name, :code, :description, :is_deleted, :team_count, :member_count, :website, :image)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, :html => {:class => 'form-horizontal', :multipart => true, :data => {:abide => true}} do |f| %>
    <div class="form-content form-below">
      <% if @project.errors.any? %>
          <div id="error_explanation">
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
      <% end %>
      <%= build_validated_field('project', 'name', 'Title', 'Cannot be blank', '[a-zA-Z]+', 'text',@project.name) %>
      <%= build_validated_field('project', 'code', 'Code', 'Cannot be blank', '[a-zA-Z]+', 'text',@project.code) %>
      <%= build_field('project', 'website', 'Url', 'text',@project.website) %>
      <%= build_field('project', 'description', 'Description', 'text_area',@project.description) %>
      <%= build_field('project', 'image', 'Image', 'file',@project.image) %>
      <%#= build_validated_field('project', 'is_deleted', 'Deleted', 'Cannot be blank', '[a-zA-Z]+', 'checkbox',@project.is_deleted) %>
      <%#= build_field('project', 'team_count', 'Teams count', 'text',@project.team_count) %>
      <%#= build_field('project', 'member_count', 'Members count', 'text',@project.member_count) %>
      <div class='form-row'>
        <div class='small-3 columns'>
          <%= f.label :user_ids, 'Managers' %>
        </div>
        <div class='small-9 columns'>
          <%= f.select :user_ids,@users.map{|x| [x.name,x.id]},{},{:multiple=>true} %>
        </div>
      </div>
    </div>
    <div class="small-12 columns form-action-up">
    <div class="title">Department</div>
      <div class="right">
        <%= f.submit 'Save', :class => 'button alert right' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    projects_path, :class => 'btn cancel-btn' %>
      </div>
    </div>
<% end %>
<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/projects/_new_link.erb
<%= link_to 'New department', new_project_path, :remote => false,:class=>'dashed_link transition' %>

app/views/projects/_project_card.erb
<%= link_to project_path(project),:remote=>false do %>
    <div class="project card-transparent transition prj-<%= project.id %>">
      <div class="cols ths">
        <%= image_tag(project.image.icon) %>
      </div>
      <div class="cols">
        <div class="title"><%= project.name %></div>
        <div class="text">
          <%= "#{project.team_count} #{'team'.pluralize(project.team_count)}" %>
          <%= "#{project.member_count} #{'team'.pluralize(project.member_count)}" %>
        </div>
        <div class="text">
          <%= project.website %>
        </div>
      </div>
    </div>
<% end %>

app/views/projects/_project_list.erb
<div class="pane2-meta">
  <div class="title">Departments</div>
</div>
<div class="pane2-content">
  <% if can? :create, Project %>
  <%= link_to 'Create department', new_project_path, :remote => false, :class => 'dashed_link transition' %>
  <% end %>
  <% projects = Project.active if projects.nil? %>
  <% projects.each do |project| %>
      <%= link_to project_path(project), :remote => false do %>
          <div class="project card-transparent transition prj-<%= project.id %>">
            <div class="cols ths">
              <%= image_tag(project.image.icon) %>
            </div>
            <div class="cols">
              <div class="title"><%= project.name %></div>
              <div class="text">
                <%= "#{project.team_count} #{'team'.pluralize(project.team_count)}" %>
                <%= "#{project.member_count} #{'member'.pluralize(project.member_count)}" %>
              </div>
              <div class="text">
                <%= project.website %>
              </div>
            </div>
          </div>
      <% end %>
  <% end %>
</div>

app/views/projects/_show.erb
<div class="pane3-padding">
  <div class="head-row project">
    <div class="cols">
      <%= image_tag(project.image.thumbnail) %>
    </div>
    <div class="right options">
      <% if can? :manage, @project %>
          <a href="#" data-options="align:left" data-dropdown="drop1" class="dropdown right">
            <div class="icon settings-link"></div>
          </a>
          <ul id="drop1" data-dropdown-content class="f-dropdown">
            <li>
              <%= link_to "Edit", edit_project_path(@project) %>
            </li>
            <li>
              <%= link_to "Delete", project_path(@project), :method => :delete,:confirm=>'Are you sure you want to archive this department?' %>
            </li>
          </ul>
      <% end %>
    </div>
    <div class="title">
      <div class="main-title"><%= project.name %></div>
      <div class="main-title-helper">(<%= project.code %>)</div>
    </div>
    <div class="website"><%= project.website %></div>
    <div class="description"><%= project.description %></div>
  </div>

  <div class="data-container">
    <dl class="tabs" data-tab>
      <dd class="active"><a href="#project-teams">
        Teams
        <div class="fig"><%= project.team_count %></div>
      </a></dd>
      <dd><a href="#project-members">
        Members
        <div class="fig"><%= project.member_count %></div>
      </a></dd>
      <dd><a href="#project-managers">
        Managers
        <div class="fig"><%= project.project_managers.count %></div>
      </a></dd>
      <div class="right meta">
        Added on
        <div class="fig"><%= project.created_at.strftime('%d %B %Y') %></div>
      </div>

    </dl>
    <div class="tabs-content">
      <div class="content active" id="project-teams">
        <%= render :partial => 'teams/team_list', :locals => {:project => @project, :teams => @teams.present? ? @teams : @project.teams} %>
      </div>
      <div class="content" id="project-members">
        <%= render :partial => 'users/user_list', :locals => {:users => @members.present? ? @members : @project.members} %>
      </div>
      <div class="content" id="project-managers">
        <%= render :partial => 'users/user_list', :locals => {:users => @managers.present? ? @managers : @project.users} %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $('.project.card').removeClass('active')
    $('.prj-<%= project.id %>').addClass('active')
</script>

app/views/projects/edit.html.erb
<%= content_for :pane2 do %>
    <%= render :partial => 'projects/project_list', :locals => {:projects => @projects} %>
<% end %>
<%= content_for :pane3 do %>
    <%= render :partial => 'form' %>
<% end %>
<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/projects/index.html.erb
<%= content_for :pane2 do %>
    <!--<div class="large-4 columns pane2">-->
    <%#= render :partial=>'projects/new_link' %>
    <%# @projects.each do |project| %>
        <%= render :partial => 'projects/project_list', :locals => {:projects => @projects} %>
    <%# end %>

    <!--</div>-->
    <!--<div class="large-6 columns pane3">-->
<% end %>
<%= content_for :pane3 do %>
    <% if @project.present? %>
        <%= render :partial => 'projects/show', :locals => {:project => @project} %>
    <% end %>
<% end %>
<!--</div>-->
<script type="text/javascript">
    window.location = '#pane2'
</script>

app/views/projects/new.html.erb
<%= content_for :pane2 do %>
    <%= render :partial => 'projects/project_list', :locals => {:projects => @projects} %>
<% end %>
<%= content_for :pane3 do %>
    <%= render :partial => 'form' %>
<% end %>
<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/projects/new.js.erb
$('.pane3').html("<%= escape_javascript(render :partial => 'projects/form',:locals=>{:project=>@project}) %>")
$(document).foundation({
    tab: {
        callback: function (tab) {
        }
    }
});
window.location = '#pane3'

app/views/projects/show.html.erb
<!--<div class="large-4 columns pane2">-->
<%= content_for :pane2 do %>
    <%# @projects.each do |project| %>
        <%= render :partial => 'projects/project_list', :locals => {:projects => @projects} %>
    <%# end %>
    <!--</div>-->
<% end %>

<!--<div class="large-6 columns pane3">-->
<%= content_for :pane3 do %>
    <% if @project.present? %>
        <%= render :partial => 'projects/show', :locals => {:project => @project} %>
    <% end %>
<% end %>
<!--</div>-->
<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/projects/show.js.erb
$('.pane3').html("<%= escape_javascript(render :partial => 'projects/show',:locals=>{:project=>@project}) %>")
$(document).foundation({
    tab: {
        callback: function (tab) {
        }
    }
});
window.location = '#pane3'