config/routes.rb
Fluxday::Application.routes.draw do

  resources :oauth_applications

  use_doorkeeper
  resources :okrs

  get "reports/index"
  get "reports/activities"
  get "reports/employees_daily"
  get "reports/employee_day"
  get "reports/employees_time_range"
  get "reports/employee_range"
  get "reports/tasks"
  get "reports/task"
  get "reports/okrs"
  get "reports/get_selection_list"
  get "reports/employee_tasks"
  get "reports/worklogs"
  get "reports/day_log"
  get "reports/assignments"

  resources :work_logs do
    member do
      post 'delete_request'
      post 'ignore_request'
    end
  end

  get "calendar/index"
  get "calendar/monthly"
  get "calendar/day"
  get "calendar/week"
  resources :comments do
    member do
      get 'reply'
      post 'post_reply'
    end
  end

  resources :tasks do
    resources :comments
    member do
      post 'completion'
    end
    collection do
      get 'completed_index'
    end
  end

  resources :teams do
    get 'add_members'
    post 'add_members'
    collection do
      get 'get_member_list'
    end
  end

  get "home/index"
  get "home/dashboard"
  get "home/search"
  post "home/search"
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  resources :projects do
    resources :teams
  end

  resources :users do
    resources :okrs do
      member do
        post 'approve'
      end
    end
    collection do
      get 'change_password'
      post 'change_password'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/me' => "credentials#me"
    end
  end

  root 'home#index'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  layout 'less_pane'


  def index
  end

  def activities
  end

  def employees_daily
    @opts = []
    if current_user.manager?
      @opts = [['Department', 'project'], ['Team', 'team'], ['Managing users', 'managing_users'], ["All employees", 'all_users'], ['Self', 'user']]
    else
      @opts << ['Department', 'project'] if current_user.admin_projects_count.to_i > 0
      @opts << ['Team', 'team'] if current_user.admin_teams_count.to_i > 0
      @opts << ['Managing users', 'managing_users'] if current_user.user_ids.length > 0
      @opts << ['Self', 'user']
    end
    @report_type = params[:report][:type] if params[:report].present?
    @report_type ||= current_user.manager? ? 'all_users' : 'user'
    if @report_type == 'project' && params[:report].present? && params[:report][:project_id].present?
      @projects = current_user.projects
      @project = current_user.manager? ? Project.find(params[:report][:project_id]) : @projects.find(params[:report][:project_id])
      @users = @project.members if @project.present?
    elsif @report_type == 'team' && params[:report].present? && params[:report][:team_id].present?
      @team = Team.find(params[:report][:team_id])
      @users = @team.members
    elsif @report_type == 'managing_users'
      @users = current_user.users
    elsif @report_type == 'all_users'
      @users = User.active
    elsif @report_type == 'employees' && params[:report].present? && params[:report][:user_id].present?
      @users = User.where(id: params[:report][:user_id])
    else
      @users = User.where(id: current_user.id)
    end
    @date = params[:report][:date].to_date if  (params[:report].present? && params[:report][:date].present?)
    @date ||= Date.today
    @tasks=Hash.new { |h, k| h[k] = Hash.new(&h.default_proc) }
    if @report_type == 'project'
      tasks = Task.joins(:key_results).where('tasks.start_date <= ? && tasks.end_date >= ? && key_results.user_id in (?) && project_id = ?', @date.end_of_day, @date.beginning_of_day, @users.collect(&:id), @project.id).uniq
      grouped_tasks = tasks.group_by(&:user_ids)
    elsif @report_type == 'team'
      tasks = Task.joins(:key_results).where('tasks.start_date <= ? && tasks.end_date >= ? && key_results.user_id in (?) && team_id = ?', @date.end_of_day, @date.beginning_of_day, @users.collect(&:id), @team.id).uniq
      grouped_tasks = tasks.group_by(&:user_ids)
    else
      tasks = Task.joins(:key_results).where('tasks.start_date <= ? && tasks.end_date >= ? && key_results.user_id in (?)', @date.end_of_day, @date.beginning_of_day, @users.collect(&:id)).uniq
      grouped_tasks = tasks.group_by(&:user_ids)
    end
    grouped_tasks.keys.each { |x| x.each { |y| @tasks[y]=grouped_tasks[x] } }
    @work_logs = Hash.new { |h, k| h[k] = Hash.new(&h.default_proc) }
    work_logs = WorkLog.where(date: @date, user_id: @users.collect(&:id), task_id: tasks.collect(&:id)).select('id', 'user_id', 'minutes').group_by(&:user_id)
    work_logs.each { |x, v| @work_logs[x]="#{v.sum(&:minutes).to_duration}" }
    #work_logs.keys.each{|x| @work_logs[x]="#{work_logs[x].sum(&:minutes).to_i/60}:#{work_logs[x].sum(&:minutes).to_i%60}"}
    if ['csv', 'xls'].include?(request.format)
      @titles = ["Name", "Task", "Total hours"]
      @fields=[]
      @users.each do |user|
        @fields << ["#{user.name}", "#{@tasks[user.id].length}", "#{@work_logs[user.id] == {} ? "0:00" : @work_logs[user.id].to_i.to_duration}"]
      end
    end
    respond_to do |format|
      format.js { render :layout => false }
      format.html
      format.csv do
        response.headers['Content-Disposition'] = 'attachment; filename="okr_report.csv"'
        render "reports/csv_report.csv.erb"
      end
      format.xls do
        response.headers['Content-Disposition'] = 'attachment; filename="okr_report.xls"'
        render "reports/excel_report.xls.erb"
      end
      format.pdf { render :pdf => "Fluxday report", :page_size => 'A4', :show_as_html => params[:debug].present?, :disable_javascript => false, :layout => 'pdf.html', :footer => {:center => '[page] of [topage]'} }
    end
  end

  def employees_time_range
    @opts = []
    if current_user.manager?
      @opts = [['Department', 'project'], ['Team', 'team'], ['Managing users', 'managing_users'], ["All employees", 'all_users'], ['Self', 'user']]
    else
      @opts << ['Department', 'project'] if current_user.admin_projects_count.to_i > 0
      @opts << ['Team', 'team'] if current_user.admin_teams_count.to_i > 0
      @opts << ['Managing users', 'managing_users'] if current_user.user_ids.length > 0
      @opts << ['Self', 'user']
    end
    @report_type = params[:report][:type] if params[:report].present?
    @report_type ||= current_user.manager? ? 'all_users' : 'user'
    if @report_type == 'project' && params[:report].present? && params[:report][:project_id].present?
      @projects = current_user.projects
      @projects = Project.active if current_user.manager?
      @project = @projects.find(params[:report][:project_id])
      @users = @project.members if @project.present?
    elsif @report_type == 'team' && params[:report].present? && params[:report][:team_id].present?
      @team = Team.find(params[:report][:team_id])
      @users = @team.members
    elsif @report_type == 'managing_users'
      @users = current_user.users
    elsif @report_type == 'all_users'
      @users = User.active
    elsif @report_type == 'employees' && params[:report].present? && params[:report][:user_id].present?
      @users = User.where(id: params[:report][:user_id])
    else
      @users = User.where(id: current_user.id)
    end
    @start_date = params[:report][:start_date].to_date if  (params[:report].present? && params[:report][:start_date].present?)
    @end_date = params[:report][:end_date].to_date if  (params[:report].present? && params[:report][:end_date].present?)
    @start_date ||= Date.today.beginning_of_month
    @end_date ||= Date.today.end_of_month
    @tasks= {} #Hash.new { |h, k| h[k] = Hash.new(&h.default_proc) }
    if @report_type == 'project'
      tasks = Task.joins(:key_results).where('project_id = ? && tasks.start_date <= ? && tasks.end_date >= ? && key_results.user_id in (?)', @project.id, @end_date.end_of_day, @start_date.beginning_of_day, @users.collect(&:id)).includes(:users).uniq
      grouped_tasks = tasks.group_by(&:user_ids)
    elsif @report_type == 'team'
      tasks = Task.joins(:key_results).where('team_id = ? && tasks.start_date <= ? && tasks.end_date >= ? && key_results.user_id in (?)', @team.id, @end_date.end_of_day, @start_date.beginning_of_day, @users.collect(&:id)).includes(:users).uniq
      grouped_tasks = tasks.group_by(&:user_ids)
    else
      tasks = Task.joins(:key_results).where('tasks.start_date <= ? && tasks.end_date >= ? && key_results.user_id in (?)', @end_date.end_of_day, @start_date.beginning_of_day, @users.collect(&:id)).includes(:users).uniq
      grouped_tasks = tasks.group_by(&:user_ids)
    end
    grouped_tasks.keys.each { |x| x.each { |y| @tasks[y]= @tasks[y].to_i + grouped_tasks[x].length } }
    @work_logs = Hash.new { |h, k| h[k] = Hash.new(&h.default_proc) }
    work_logs = WorkLog.where(date: @start_date..@end_date, user_id: @users.collect(&:id), task_id: tasks.collect(&:id)).select('id', 'user_id', 'minutes').group_by(&:user_id)
    work_logs.each { |x, v| @work_logs[x]="#{v.sum(&:minutes).to_i.to_duration}" }
    #work_logs.keys.each{|x| @work_logs[x]="#{work_logs[x].sum(&:minutes).to_i/60}:#{work_logs[x].sum(&:minutes).to_i%60}"}
    if ['csv', 'xls'].include?(request.format)
      @titles = ["Name", "Task", "Total hours"]
      @fields=[]
      @users.each do |user|
        @fields << ["#{user.name}", "#{@tasks[user.id].to_i}", "#{@work_logs[user.id] == {} ? "0:00" : @work_logs[user.id].to_i.to_duration}"]
      end
    end
    respond_to do |format|
      format.js { render :layout => false }
      format.html
      format.csv do
        response.headers['Content-Disposition'] = 'attachment; filename="okr_report.csv"'
        render "reports/csv_report.csv.erb"
      end
      format.xls do
        response.headers['Content-Disposition'] = 'attachment; filename="okr_report.xls"'
        render "reports/excel_report.xls.erb"
      end
      format.pdf { render :pdf => "Fluxday report", :page_size => 'A4', :show_as_html => params[:debug].present?, :disable_javascript => false, :layout => 'pdf.html', :footer => {:center => '[page] of [topage]'} }
    end
  end


  def employee_day
    if current_user.manager?
      @users = User.active
    else
      @users = ([current_user]+current_user.users).uniq
    end
    @user=User.find(params[:employee_id]) if params[:employee_id]
    @user ||= @users.first
    @date = params[:start_date].to_date if  params[:start_date].present?
    @date ||= Date.today
    @work_logs = WorkLog.where(date: @date, user_id: @user.id).includes(:task => [:project, :team])
    if ['csv', 'xls'].include?(request.format)
      @titles = ["Task", "Department", "Team", "Hours", "Status"]
      @fields=[]
      @work_logs.each do |log|
        @fields << ["#{log.task.name}", "#{log.task.project.name}", "#{log.task.team.name}", "#{log.hours}", "#{log.task.status == 'active' ? 'Pending' : log.task.status.capitalize}"]
      end
    end
    respond_to do |format|
      format.js { render :layout => false }
      format.html
      format.csv do
        response.headers['Content-Disposition'] = 'attachment; filename="okr_report.csv"'
        render "reports/csv_report.csv.erb"
      end
      format.xls do
        response.headers['Content-Disposition'] = 'attachment; filename="okr_report.xls"'
        render "reports/excel_report.xls.erb"
      end
      format.pdf { render :pdf => "Fluxday report", :page_size => 'A4', :show_as_html => params[:debug].present?, :disable_javascript => false, :layout => 'pdf.html', :footer => {:center => '[page] of [topage]'} }
    end
  end

  def employee_range

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_assignments.erb
<% unless @users.empty? %>
    <div class="export-options">
      <%= link_to "PDF", current_url(:format => :pdf), :target => "_blank" %>
      <%= link_to "CSV", current_url(:format => :csv), :target => "_blank" %>
      <%= link_to "Excel", current_url(:format => :xls), :target => "_blank" %>
    </div>
    <div class="report">

      <table class="table sortable-table">
        <thead>
        <tr>
          <th width="150">Tracker id</th>
          <th width="300">Name</th>
          <th width="150">Start date</th>
          <th width="150">End date</th>
          <th width="150">Status</th>
          <th width="150">Completed on</th>
          <th width="100">Time spent</th>
          <th width="100" class="hidden_class">Time spent</th>
        </tr>
        </thead>

        <tbody>
        <% @fields.each do |f| %>
            <tr>
              <% f.to_a.each_with_index do |x,i| %>
                  <% if i == 6 %>
                    <td class="hidden_class"><%= x.nil? ? "0" : x.gsub(":","") %></td>
                  <% end %>
                <td><%= link_to x, reports_task_path(:tracker_id=>f[0],:user_id=>@user.id),:remote=>true %></td>
              <% end %>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
<% else %>
    <div class="alert-box secondary">
      No users to show.
    </div>
<% end %>
<script type="text/javascript">
    $(".sortable-table").tablesorter();
</script>

app/views/reports/_day_log.erb
<div class="big-text">
  <%= "Worklogs of #{@user.name} for #{@date.strftime("%d %B %Y")}" %>

</div>
<div class="export-options">
  <%= link_to "PDF", current_url(:format => :pdf), :target => "_blank" %>
  <%= link_to "CSV", current_url(:format => :csv), :target => "_blank" %>
  <%= link_to "Excel", current_url(:format => :xls), :target => "_blank" %>
</div>
<table class="table sortable-table">
  <thead>
  <tr>
    <th width="500">Task</th>
    <th width="200">Duration</th>
    <th width="500">Description</th>
    <th width="200">Actions</th>
  </tr>
  </thead>
  <% @work_logs.each do |log| %>
      <tr>
        <td><%= log.task.name %></td>
        <td><%= log.minutes.to_duration %></td>
        <td><%= log.description %></td>
        <% if @current_user.id == @user.id and log.delete_request == false and log.date < 4.days.ago%>
          <td><%= link_to 'Reqest Removal', delete_request_work_log_path(log), :method => :post, :confirm => 'Are you sure you want to request for removal of this log?' %></td>
        <%elsif @current_user.manager? and log.delete_request == true%>
          <td><%= link_to 'Delete', work_log_path(log), :method => :delete, :confirm => 'Are you sure you want to remove this log?' %> | <%= link_to 'Ignore', ignore_request_work_log_path(log), :method => :post, :confirm => 'Are you sure you want to ignore this request?' %></td>
        <%else%>
          <td>-</td>
        <%end%>
      </tr>
  <% end %>
</table>

app/views/reports/_employee_day.erb
<% unless @work_logs.empty? %>
    <div class="export-options">
      <%= link_to "PDF", current_url(:format => :pdf), :target => "_blank" %>
      <%= link_to "CSV", current_url(:format => :csv), :target => "_blank" %>
      <%= link_to "Excel", current_url(:format => :xls), :target => "_blank" %>
    </div>

    <table class="table sortable-table highchart" data-graph-container-before="1" data-graph-type="pie" data-graph-xaxis-rotation="-45">
      <thead>
      <tr>
        <th width="400">Task</th>
        <th data-graph-skip="1" width="300">Department</th>
        <th data-graph-skip="1" width="300">Team</th>
        <th data-graph-skip="1" width="200">Hours</th>
        <th class="hidden_class" data-graph-skip="1" width="200">Hours</th>
        <th class="hidden_class" width="200">Hours</th>
        <th data-graph-skip="1" width="200">Status</th>
      </tr>
      </thead>
      <% @work_logs.each do |log| %>
          <tr>
            <td><%= link_to log.task.name,reports_employee_tasks_path(:user_id=>@user.id,:task_id=>log.task_id,:start_date=>@date,:end_date=>@date) %></td>
            <td><%= log.task.project.name %></td>
            <td><%= log.task.team.name %></td>
            <td class="hidden_class"><%= log.hours.gsub(":","") %></td>
            <td><%= log.hours %></td>
            <td class="hidden_class"><%= log.hours.gsub(":",",") %></td>
            <td><%= log.task.status == 'active' ? 'Pending' : log.task.status.capitalize  %></td>
          </tr>
      <% end %>
    </table>
    <script type="text/javascript">
        $(".sortable-table").tablesorter();
        if ($('.table tbody tr').length > 1){$('table.highchart').highchartTable();}
    </script>

<% else %>
    <div class="alert-box secondary">
      No sufficient data yet.
    </div>
<% end %>

app/views/reports/_employee_tasks.erb
<% unless @work_logs.empty? %>
    <div class="export-options">
      <%= link_to "PDF", current_url(:format => :pdf), :target => "_blank" %>
      <%= link_to "CSV", current_url(:format => :csv), :target => "_blank" %>
      <%= link_to "Excel", current_url(:format => :xls), :target => "_blank" %>
    </div>

    <table class="table sortable-table highchart" data-graph-container-before="1" data-graph-type="pie" data-graph-xaxis-rotation="-45">
      <thead>
      <tr>
        <th  width="200">Date</th>
        <th data-graph-skip="1" width="200">Total hours</th>
        <th class="hidden_class" data-graph-skip="1" width="200">Total hours</th>
        <th class="hidden_class" width="200">Total hours</th>
        <th data-graph-skip="1" width="800">Description</th>
      </tr>
      </thead>
      <% @work_logs.each do |log| %>
          <tr>
            <td><%= log.date.strftime('%d %B %Y') %></td>
            <td class="hidden_class"><%= log.hours.gsub(":","") %></td>
            <td><%= log.hours %></td>
            <td class="hidden_class"><%= log.hours.gsub(":",",") %></td>
            <td><%= log.description %></td>
          </tr>
      <% end %>
    </table>
    <script type="text/javascript">
        $(".sortable-table").tablesorter();
        if ($('.table tbody tr').length > 1){$('table.highchart').highchartTable();}
    </script>
<% else %>
    <div class="alert-box secondary">
      No sufficient data yet.
    </div>
<% end %>

app/views/reports/_selections.erb
<% if @projects.present? %>
    <%= select_tag 'report[project_id]', options_for_select(@projects.map { |x| [x.name, x.id] }), :class => 'report_type_select' %>
<% elsif @teams.present? %>
    <%= select_tag 'report[team_id]', options_for_select(@teams.map { |x| [x.name, x.id] }), :class => 'report_type_select' %>
<% elsif @users.present? %>
    <%= select_tag 'report[user_id]', options_for_select(@users.map { |x| [x.name, x.id] }), :class => 'report_type_select' %>
<% else %>

<% end %>

app/views/reports/csv_report.csv.erb
<%= @titles.join(",") %>
<% @fields.each do |f| %>
<%#= f.join(',') %>
<%= f.map(&:inspect).join(', ').html_safe %>
<% end %>

app/views/reports/day_log.js.erb
<% if @user.present? %>
$('.modal-content').html("<%= escape_javascript(render :partial => 'reports/day_log') %>")
$('#myModal').foundation('reveal', 'open');
<% else %>
$('.alert-area').notify({message: { text: 'Access denied' }, type: 'tracker-alert', fadeOut: { enabled: true, delay: 10000 }}).show();
<% end %>

app/views/reports/employees_daily.html.erb
<div class="main-title">
  <div class="element">
    <h5>Reports
    <a href="#" data-dropdown="drop1" class="report-select">Grouped Employee daily report  ▾</a>
    <ul id="drop1" class="f-dropdown report-select" data-dropdown-content>
      <%= render 'reports/report_types' %>
    </ul>
    </h5>
  </div>
</div>
<div class="report-options">
  <!--<form class="employee_daily_report_form" data-remote="true">-->
    <%= form_for(:report, :url => {:controller => 'reports', :action => 'employees_daily'},:method=>:get,:remote=>true, :class => 'employee_daily_report_form') do %>
    <div class="report-type">
          <%= select_tag 'report[type]', options_for_select(@opts, @report_type), :class => 'report_type_select' %>
    </div>
    <div class="report_options">

    </div>
    <div class="submit_button  show-for-medium-up">
      <button>Go</button>
    </div>
    <div class="report-date">
      <%= text_field_tag 'report[date]', @date, :class => 'date-only-input' %>
    </div>
      <div class="submit_button show-for-small-only">
        <button>Go</button>
      </div>
      <% end %>
  <!--</form>-->
</div>
<div class="report-renderer">
  <%= render :partial => 'reports/employee_daily' %>
</div>
<script type="text/javascript">
    $('.report_type_select').on("change", function () {
        $.get('/reports/get_selection_list?type=' + $(this).val())
    });
</script>

app/views/reports/employees_time_range.html.erb
<div class="main-title">
  <div class="element">
    <h5>Reports
      <a href="#" data-dropdown="drop1" class="report-select">Grouped Employee report for a time range  ▾</a>
      <ul id="drop1" class="f-dropdown report-select" data-dropdown-content>
        <%= render 'reports/report_types' %>
      </ul>
    </h5>
  </div>
</div>
<div class="report-options">
  <!--<form class="employee_daily_report_form" data-remote="false">-->
  <%= form_for(:report, :url => {:controller => 'reports', :action => 'employees_time_range'}, :method => :get, :remote => true, :class => 'employee_daily_report_form') do %>
      <div class="report-type">
            <%= select_tag 'report[type]', options_for_select(@opts, @report_type), :class => 'report_type_select' %>
      </div>
      <div class="report_options">

      </div>
      <div class="submit_button  show-for-medium-up">
        <button>Go</button>
      </div>
      <div class="report-date">
        <%= text_field_tag 'report[start_date]', @start_date, :class => 'date-only-input' %>
        <%= text_field_tag 'report[end_date]', @end_date, :class => 'date-only-input' %>
      </div>
      <div class="submit_button show-for-small-only">
        <button>Go</button>
      </div>
  <% end %>
  <!--</form>-->
</div>
<div class="report-renderer">
  <%= render :partial => 'reports/employee_time_range' %>
</div>
<script type="text/javascript">
    $('.report_type_select').on("change", function () {
        $.get('/reports/get_selection_list?type=' + $(this).val())
    });
</script>

app/views/reports/okrs.html.erb
<div class="main-title">
  <div class="element">
    <h5>Reports
      <a href="#" data-dropdown="drop1" class="report-select">OKR report  ▾</a>
      <ul id="drop1" class="f-dropdown report-select" data-dropdown-content>
        <%= render 'reports/report_types' %>
      </ul>
    </h5>
  </div>
</div>
<div class="report-options">
  <!--<form class="employee_daily_report_form" data-remote="false">-->
  <%= form_for(:report, :url => {:controller => 'reports', :action => 'okrs'},:method=>:get,:remote=>true, :class => 'employee_daily_report_form') do %>
      <div class="report-type">
        <%= select_tag('employee_id', options_for_select(@users.map { |x| [x.name, x.id] }, @user.id)) %>
      </div>
      <div class="submit_button  show-for-medium-up">
        <button>Go</button>
      </div>
      <div class="report-date">
        <%= text_field_tag 'start_date', @start_date, :class => 'date-only-input' %>
        <%= text_field_tag 'end_date', @end_date, :class => 'date-only-input' %>
      </div>
      <div class="submit_button show-for-small-only">
        <button>Go</button>
      </div>
      <!--</form>-->
  <% end %>
</div>
<div class="report-renderer">
  <%= render :partial => 'reports/okr_report' %>
</div>

app/views/reports/okrs.pdf.erb
<div class="title">
  OKR report
</div>
<div class="page-break">
  <%= render :partial => 'reports/okr_report' %>
</div>

app/views/reports/worklog_detailed.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <%= @titles.each do |t| %>
            <Cell>
              <Data ss:Type="Text"><%= t %></Data>
            </Cell>
        <% end %>
      </Row>
      <% @users.each do |user| %>
          <% unless @user_rows[user.id].nil? %>
              <% (0..(@user_rows[user.id]-1)).each do |i| %>
                  <Row>
                    <Cell>
                      <Data ss:Type="Text"><%= user.name %></Data>
                    </Cell>
                    <% (@start_date..@end_date).each do |dt| %>
                        <% unless @user_logs[user.id][dt.day][i].blank? %>
                            <Cell>
                              <% unless @user_logs[user.id][dt.day][i].nil? %>
                                  <Data ss:Type="Text"><%= "#{@user_logs[user.id][dt.day][i][0]} - #{@user_logs[user.id][dt.day][i][1]}" %></Data>
                              <% end %>
                            </Cell>
                        <% else %>
                            <Cell><Data ss:Type="Text">-</Data></Cell>
                        <% end %>
                    <% end %>
                  </Row>
              <% end %>
              <Row>
                <Cell>
                  <Data ss:Type="Text" ss:Bold="1"><%= "#{user.name} - Total" %></Data>
                </Cell>
                <% (@start_date..@end_date).each do |dt| %>
                    <Cell>
                      <% unless @hours[user.id][dt.day].blank? %>
                          <Data ss:Type="Text"><%= @hours[user.id][dt.day]["hours"].to_i.to_duration %></Data>
                      <% end %>
                    </Cell>
                <% end %>
                <Cell>
                  <Data ss:Type="Text"><%= @average[user.id] %></Data>
                </Cell>
                <Cell>
                  <Data ss:Type="Text"><%= @total[user.id].to_duration %></Data>
                </Cell>
              </Row>
          <% end %>
      <% end %>
    </Table>
  </Worksheet>
  <Worksheet ss:Name="Sheet2">
    <Table>
      <Row>
        <%= @titles.each do |t| %>
            <Cell>
              <Data ss:Type="Text"><%= t %></Data>
            </Cell>
        <% end %>
      </Row>
      <% @fields.each do |f| %>
          <Row>
            <% f.each do |val| %>
                <Cell>
                  <Data ss:Type="Text"><%= val %></Data>
                </Cell>
            <% end %>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/reports/worklogs.html.erb
<div class="main-title">
  <div class="element">
    <h5>Reports
      <a href="#" data-dropdown="drop1" class="report-select">Worklogs  ▾</a>
      <ul id="drop1" class="f-dropdown report-select" data-dropdown-content>
        <%= render 'reports/report_types' %>
      </ul>
    </h5>
  </div>
</div>
<div class="report-options">
  <!--<form class="employee_daily_report_form" data-remote="false">-->
  <%= form_for(:report, :url => {:controller => 'reports', :action => 'worklogs'}, :method => :get, :remote => true, :class => 'employee_daily_report_form') do %>
      <div class="report-type">
        <%= select_tag 'report[type]', options_for_select(@opts, @report_type), :class => 'report_type_select' %>
      </div>
      <div class="report_options">

      </div>

      <div class="submit_button  show-for-medium-up">
        <button>Go</button>
      </div>
      <div class="report-date">
        <%= select_tag 'month', options_for_select(Date::MONTHNAMES,@start_date.strftime('%B')),:class=>'month' %>
        <%= select_tag 'year', options_for_select((2010..2050),@start_date.year),:class=>'year' %>
      </div>

      <div class="submit_button show-for-small-only">
        <button>Go</button>
      </div>
  <% end %>
  <!--</form>-->
</div>

<div class="report-renderer worklog-report">
  <%= render :partial => 'reports/worklogs' %>
</div>
<script type="text/javascript">
    $('.report_type_select').on("change", function () {
        $.get('/reports/get_selection_list?type=' + $(this).val())
    });
</script>

app/views/reports/worklogs.pdf.erb
<div class="title">
  OKR report
</div>
<div class="page-break">
  <%= render :partial => 'reports/worklogs' %>
</div>